name: 6-hourly-cron-schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://roll-some-dice.vercel.app/api/cron' \