name: login-schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route for login
        run: |
          curl --request GET \
          --url 'https://roll-some-dice.vercel.app/api/cron' \